version: '3.8'

services:
  backend:
    build: ./Hologram-backend
    image: hologramdev.azurecr.io/hologram-backend:dev
    container_name: hologram-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: always

  frontend:
    build: ./Hologram-frontend
    image: hologramdev.azurecr.io/hologram-frontend:dev
    container_name: hologram-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend
    restart: always
