FROM node:20-alpine

WORKDIR /usr/src/app

# Install cpx first, so it's available when postinstall runs
RUN npm install -g cpx

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev"]
